# Generated by Django 5.0 on 2023-12-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SHIPPED', 'SHIPPED'), ('CANCELLED', 'CANCELLED')], max_length=20),
        ),
    ]
