# Generated by Django 5.0 on 2023-12-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_id', models.CharField(max_length=20)),
                ('ord_dt', models.DateField()),
                ('qt_ordd', models.IntegerField()),
            ],
        ),
    ]
